version: '3.9'

services:
  zundacord:
    build:
      target: app
    init: true
    environment:
      ZUNDACORD_DISCORD_TOKEN: ${ZUNDACORD_DISCORD_TOKEN}
      ZUNDACORD_VOICEVOX_API_ENDPOINT: "http://voicevox:50021"
    volumes:
      - type: bind
        source: ./config
        target: /workspaces/zundacord/config
    restart: unless-stopped
  
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "80:50021"
    restart: unless-stopped
